INSERT INTO suppliers (supplier_id, supplier_name, supplier_phone, supplier_email) VALUES (1, 'Rodriguez, Figueroa and Sanchez', '(181)960-0133', 'hoffmanjennifer@gardner.com');
INSERT INTO suppliers (supplier_id, supplier_name, supplier_phone, supplier_email) VALUES (2, 'Wolfe LLC', '235-116-1559x407', 'dudleynicholas@carter.com');
INSERT INTO suppliers (supplier_id, supplier_name, supplier_phone, supplier_email) VALUES (3, 'Lee, Jones and Stanley', '001-413-164-7525x53419', 'amandasanchez@gray-mayo.net');
INSERT INTO suppliers (supplier_id, supplier_name, supplier_phone, supplier_email) VALUES (4, 'Cohen Inc', '056.413.9537', 'pwilkerson@thomas-taylor.net');
INSERT INTO suppliers (supplier_id, supplier_name, supplier_phone, supplier_email) VALUES (5, 'Baker, Richards and Hurst', '(532)871-0122x6916', 'dcarlson@king.com');
INSERT INTO suppliers (supplier_id, supplier_name, supplier_phone, supplier_email) VALUES (6, 'Dyer, Potter and Mack', '146-270-4828x14893', 'nathanielmartin@sellers.com');
INSERT INTO suppliers (supplier_id, supplier_name, supplier_phone, supplier_email) VALUES (7, 'Koch-Decker', '303-911-7182x2782', 'allison96@hickman.com');
INSERT INTO suppliers (supplier_id, supplier_name, supplier_phone, supplier_email) VALUES (8, 'Collins, Carney and Santos', '871.331.5098x393', 'jonescrystal@jones.com');
INSERT INTO suppliers (supplier_id, supplier_name, supplier_phone, supplier_email) VALUES (9, 'Palmer LLC', '+1-738-299-7376x31165', 'ujenkins@nunez.com');
INSERT INTO suppliers (supplier_id, supplier_name, supplier_phone, supplier_email) VALUES (10, 'Powell LLC', '333-872-6247', 'nancyjones@garcia.com');
INSERT INTO suppliers (supplier_id, supplier_name, supplier_phone, supplier_email) VALUES (11, 'House and Sons', '(677)360-2606', 'sara74@horton-cross.net');
INSERT INTO suppliers (supplier_id, supplier_name, supplier_phone, supplier_email) VALUES (12, 'Higgins, Moore and Phillips', '9805009788', 'brianromero@jones.com');
INSERT INTO suppliers (supplier_id, supplier_name, supplier_phone, supplier_email) VALUES (13, 'Wilson-Zamora', '990.916.9985', 'james53@foster-powers.com');
INSERT INTO suppliers (supplier_id, supplier_name, supplier_phone, supplier_email) VALUES (14, 'Stewart-Walton', '079-911-8384', 'sarahibarra@wood.info');
INSERT INTO suppliers (supplier_id, supplier_name, supplier_phone, supplier_email) VALUES (15, 'Warner, Carr and Archer', '+1-808-412-4118x2449', 'jenniferharris@farrell.com');
INSERT INTO suppliers (supplier_id, supplier_name, supplier_phone, supplier_email) VALUES (16, 'Walters LLC', '0524278680', 'jonesnicole@gardner.org');
INSERT INTO suppliers (supplier_id, supplier_name, supplier_phone, supplier_email) VALUES (17, 'Hernandez, Anderson and Parker', '5331586923', 'theresacochran@johnson-doyle.com');
INSERT INTO suppliers (supplier_id, supplier_name, supplier_phone, supplier_email) VALUES (18, 'Pham-Shields', '421.607.3375', 'lori33@keller.com');
INSERT INTO suppliers (supplier_id, supplier_name, supplier_phone, supplier_email) VALUES (19, 'Lin-Rasmussen', '586-850-1429x401', 'yreed@graham-joyce.com');
INSERT INTO suppliers (supplier_id, supplier_name, supplier_phone, supplier_email) VALUES (20, 'Lam-Lee', '6088356159', 'elizabeth14@parker.com');
INSERT INTO suppliers (supplier_id, supplier_name, supplier_phone, supplier_email) VALUES (21, 'Martinez, Fisher and Bentley', '+1-299-468-0443x69957', 'nramos@kennedy.com');
INSERT INTO suppliers (supplier_id, supplier_name, supplier_phone, supplier_email) VALUES (22, 'Miller, Robertson and Schultz', '134-332-0037x91769', 'jennifercruz@sanchez-douglas.com');
INSERT INTO suppliers (supplier_id, supplier_name, supplier_phone, supplier_email) VALUES (23, 'Osborne and Sons', '(870)831-7278', 'stephanie79@mcclain.info');
INSERT INTO suppliers (supplier_id, supplier_name, supplier_phone, supplier_email) VALUES (24, 'Manning Group', '434.873.4714x345', 'patricia12@hall.com');
INSERT INTO suppliers (supplier_id, supplier_name, supplier_phone, supplier_email) VALUES (25, 'Lewis, Perry and Rivera', '603.669.0967x054', 'acastaneda@adkins.com');
INSERT INTO suppliers (supplier_id, supplier_name, supplier_phone, supplier_email) VALUES (26, 'Robinson-Graham', '6562729806', 'millerroy@white-green.com');
INSERT INTO suppliers (supplier_id, supplier_name, supplier_phone, supplier_email) VALUES (27, 'Gibson LLC', '001-646-417-0805x31003', 'maryhowell@martinez.com');
INSERT INTO suppliers (supplier_id, supplier_name, supplier_phone, supplier_email) VALUES (28, 'Gould, Marshall and Scott', '(299)124-1904x966', 'charlesvaughn@sanchez.org');
INSERT INTO suppliers (supplier_id, supplier_name, supplier_phone, supplier_email) VALUES (29, 'Hogan PLC', '5865185067', 'hamiltonmichael@zimmerman-graham.net');
INSERT INTO suppliers (supplier_id, supplier_name, supplier_phone, supplier_email) VALUES (30, 'Nelson, Morton and Medina', '769.453.1473x7996', 'anthony52@lewis-salinas.com');
INSERT INTO suppliers (supplier_id, supplier_name, supplier_phone, supplier_email) VALUES (31, 'Beard-Haynes', '808-313-6783x777', 'davisjeffrey@sanchez.net');
INSERT INTO suppliers (supplier_id, supplier_name, supplier_phone, supplier_email) VALUES (32, 'Cooper, Barajas and Pierce', '(744)431-3518x233', 'lhill@carlson.com');
INSERT INTO suppliers (supplier_id, supplier_name, supplier_phone, supplier_email) VALUES (33, 'Ward LLC', '8240084271', 'andrewstaylor@peterson-sheppard.com');
INSERT INTO suppliers (supplier_id, supplier_name, supplier_phone, supplier_email) VALUES (34, 'Wilson-Jones', '190.229.4131x8699', 'kimberlyjames@evans-chapman.biz');
INSERT INTO suppliers (supplier_id, supplier_name, supplier_phone, supplier_email) VALUES (35, 'Carroll-Brown', '001-133-412-3281x2067', 'ocarter@mann-warner.info');
INSERT INTO suppliers (supplier_id, supplier_name, supplier_phone, supplier_email) VALUES (36, 'Mcdaniel LLC', '+1-936-183-2421x0249', 'scott74@powell.info');
INSERT INTO suppliers (supplier_id, supplier_name, supplier_phone, supplier_email) VALUES (37, 'George Group', '001-594-013-9904x9027', 'lmoon@graham.info');
INSERT INTO suppliers (supplier_id, supplier_name, supplier_phone, supplier_email) VALUES (38, 'Ortiz-Morris', '256-746-8071', 'johnny16@bryan.info');
INSERT INTO suppliers (supplier_id, supplier_name, supplier_phone, supplier_email) VALUES (39, 'Brown-Stone', '+1-770-348-2477x109', 'jennifercollins@tran.com');
INSERT INTO suppliers (supplier_id, supplier_name, supplier_phone, supplier_email) VALUES (40, 'Murray Inc', '+1-274-846-7737x8263', 'michellehill@morgan-french.com');
INSERT INTO suppliers (supplier_id, supplier_name, supplier_phone, supplier_email) VALUES (41, 'Campbell LLC', '001-972-787-5588', 'ugibson@pollard.org');
INSERT INTO suppliers (supplier_id, supplier_name, supplier_phone, supplier_email) VALUES (42, 'Hall-Rowe', '5766270289', 'molly71@lozano.com');
INSERT INTO suppliers (supplier_id, supplier_name, supplier_phone, supplier_email) VALUES (43, 'Harrison LLC', '961-586-5780x91343', 'hamiltoncorey@padilla.com');
INSERT INTO suppliers (supplier_id, supplier_name, supplier_phone, supplier_email) VALUES (44, 'Williams Inc', '556-238-6922x2196', 'tyleraguilar@murray.info');
INSERT INTO suppliers (supplier_id, supplier_name, supplier_phone, supplier_email) VALUES (45, 'Estrada-Nolan', '482.175.9464x743', 'gcastaneda@james.org');
INSERT INTO suppliers (supplier_id, supplier_name, supplier_phone, supplier_email) VALUES (46, 'Haney-Phillips', '+1-640-909-7439x53394', 'courtneyberger@williams.com');
INSERT INTO suppliers (supplier_id, supplier_name, supplier_phone, supplier_email) VALUES (47, 'Anderson, Browning and Murphy', '(232)858-8424x74517', 'taylortammy@ramsey.net');
INSERT INTO suppliers (supplier_id, supplier_name, supplier_phone, supplier_email) VALUES (48, 'Davis-Foster', '817-549-6513x709', 'rose31@colon.biz');
INSERT INTO suppliers (supplier_id, supplier_name, supplier_phone, supplier_email) VALUES (49, 'Taylor Inc', '711-382-6758x6926', 'basschristina@johnson-wood.info');
INSERT INTO suppliers (supplier_id, supplier_name, supplier_phone, supplier_email) VALUES (50, 'Sampson-Foley', '585-064-3171', 'darleneharper@williams.com');
